meta:
  title: franrose 
  description: franrose website

user:
  username-prefix: its
  username: '<span style="color: #4c6349;">f</span>ran<span style="color: #4c6349;">r</span>ose'
  name: Mehdi Rafee
  short-description: '<span style="color: #d1443d;">enthusiastic</span> • <span style="color: #e38b3d;">adventurous</span>'
  title: programmer

about:
  description: >
    Hi there, I'm a progammer based in Isfahan, Iran - endlessly curious, easily distracted by intriguing problems, and mostly up for a challenge.<br>
    I'm fascinated by
    <span style="color: #e36f6f;">o</span>pen-source <span style="color: #e36f6f;">s</span>oftware,
    <span style="color: #6fe3df;">s</span>ystems <span style="color: #6fe3df;">p</span>rogramming,
    and <span style="color: #9a6fe3;">t</span>ooling & <span style="color: #c06fe3">t</span>inkering
    - the kind of things that make hours disappear without noticing.<br>
    An unquenchable thirst drives me to venture in the world of forms - the kind that starts with a question and ends three rabbit holes later.<br>
    Currently I'm working on my <span style="color: #84e36f;">p</span>ersonal <span style="color: #84e36f;">d</span>evelopment <span style="color: #84e36f;">e</span>cosystem,
    and brushing up on my <span style="color: #e36fa1;">w</span>eb <span style="color: #e36fa1;">d</span>evelopment skills.<br>
    Anyhow, let's get going with the professional button-pressing, shall we?

footer:
  quote: 'To be a fruitful field is to let no experience rot in vain:<br>all suffering ferment into becoming. <span style="color: #b06363;">&Friedrich Nietzsche</span>'

theme: jekyll-github-pages
