meta:
  title: franrose 
  description: francis's page

user:
  username: '<span style="color: #e9a467;">f</span>ran<span style="color: #de7873;">r</span>ose'
  name: mehdi rafee
  short-description: '<span style="color: #d1443d;">enthusiastic</span> • <span style="color: #e38b3d;">adventurous</span>'
  title: programmer
  description: >
    hi there, i'm a progammer based in isfahan, iran; passionate about
    open-source software, systems programming, and tooling & tinkering.
    currently i'm working on my personal development ecosystem,
    and brushing up on my web development skills.
    <br>anyhow, let's get going with the professional button-pressing, shall we?

footer:
  quote: 'never give up without a fight. <span style="color: #9e7b52;">&general iroh</span>'

particles: true
theme: jekyll-github-pages
