name: Build and deploy Jekyll site

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout theme repository
        # checks out the public repo itsfranrose/jekyll-github-pages into ./theme
        uses: actions/checkout@v4
        with:
          repository: itsfranrose/jekyll-github-pages
          path: theme
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Tell Bundler to use local theme path
        run: bundle config local.jekyll-github-pages ./theme

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build site with Jekyll
        run: bundle exec jekyll build --verbose

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
